package cli

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/yasyf/cc-context/internal/render"
	"github.com/yasyf/cc-context/internal/vcstest"
)

const regenCat = "cat src/*.txt > gen/out.txt"

var regenMissingSrc = regexp.MustCompile(`cat: '?src/\*\.txt'?: No such file or directory`)

func regenRepo(t *testing.T, run string) *vcstest.Fixture {
	t.Helper()
	f := shipGTRepo(t)
	writeShipFile(t, f.Dir, regenFile, fmt.Sprintf("[[generated]]\npaths = [\"gen/*.txt\"]\nrun = %q\n", run))
	writeShipFile(t, f.Dir, "src/a.txt", "a\n")
	writeShipFile(t, f.Dir, "gen/out.txt", "a\n")
	writeShipFile(t, f.Dir, "gen/other.txt", "other\n")
	mustRun(t, f.Env(), f.Dir, "git", "add", "-A")
	mustRun(t, f.Env(), f.Dir, "git", "commit", "-qm", "generated")
	mustRun(t, f.Env(), f.Dir, "git", "push", "-q", "origin", "main")
	return f
}

func regenBranch(t *testing.T, f *vcstest.Fixture, files map[string]string, removed ...string) {
	t.Helper()
	mustRun(t, f.Env(), f.Dir, "git", "switch", "-qc", "feature")
	for name, content := range files {
		writeShipFile(t, f.Dir, name, content)
	}
	for _, name := range removed {
		mustRun(t, f.Env(), f.Dir, "git", "rm", "-q", name)
	}
	mustRun(t, f.Env(), f.Dir, "git", "add", "-A")
	mustRun(t, f.Env(), f.Dir, "git", "commit", "-qm", "feature")
	mustRun(t, f.Env(), f.Dir, "gt", "track", "-f", "--no-interactive")
}

func regenAdvanceTrunk(t *testing.T, f *vcstest.Fixture, files ...[2]string) {
	t.Helper()
	for _, file := range files {
		restackAdvanceRemote(t, f, "main", file[0], file[1])
	}
	mustRun(t, f.Env(), f.Dir, "git", "fetch", "-q", "origin")
	shipResetLog(t, f)
}

func regenMarked(t *testing.T, run string) (string, string) {
	t.Helper()
	marker := filepath.Join(t.TempDir(), "ran")
	return fmt.Sprintf("echo ran >> '%s'; %s", marker, run), marker
}

func regenRuns(t *testing.T, marker string) int {
	t.Helper()
	raw, err := os.ReadFile(marker)
	if errors.Is(err, fs.ErrNotExist) {
		return 0
	}
	if err != nil {
		t.Fatal(err)
	}
	return strings.Count(string(raw), "ran\n")
}

func regenStop(t *testing.T, f *vcstest.Fixture) (string, error) {
	t.Helper()
	feature := gitAt(t, f.Env(), f.Dir, "rev-parse", "feature")
	_, _, err := runStackCmd(t, f, "rebase", "--no-push")
	if err == nil {
		t.Fatal("stack rebase succeeded, want the conflict to stop it")
	}
	if got := gitAt(t, f.Env(), f.Dir, "rev-parse", "feature"); got != feature {
		t.Errorf("feature moved to %s on a stopped rebase", got)
	}
	return stackWorkspaceOf(t, err), err
}

func regenSection(cmd string) string {
	return "generated by " + regenFile + ":\n  gen/out.txt" + shipSep + cmd + "\nregenerate: ccx vcs stack regenerate"
}

func TestStackRebasePlansAStopForAGeneratedConflict(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		files   map[string]string
		removed []string
		trunk   [][2]string
		want    bool
	}{
		{"changed on both sides", map[string]string{"src/f.txt": "f\n", "gen/out.txt": "a\nf\n"}, nil, [][2]string{{"src/t.txt", "t\n"}, {"gen/out.txt", "a\nt\n"}}, true},
		{"deleted by the branch", nil, []string{"gen/out.txt"}, [][2]string{{"gen/out.txt", "a\nt\n"}}, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			f := regenRepo(t, regenCat)
			regenBranch(t, f, tt.files, tt.removed...)
			regenAdvanceTrunk(t, f, tt.trunk...)

			plan, _, err := runStackCmd(t, f, "rebase", "--dry-run")
			if err != nil {
				t.Fatalf("dry run: %v", err)
			}
			line := "feature" + shipSep + "gen/out.txt generated" + shipSep + "a conflict there stops for ccx vcs stack regenerate" + shipSep + regenCat
			if got := strings.Contains(plan, line); got != tt.want {
				t.Errorf("plan = %q, want line %q present = %v", plan, line, tt.want)
			}
			if !tt.want && strings.Contains(plan, "generated") {
				t.Errorf("plan = %q, want no generated line for a path the branch deletes", plan)
			}
		})
	}
}

// TestStackRebaseStopsOnAGeneratedOnlyConflict pins the explicit-only design:
// a conflict every generator could settle still stops, and neither the rebase
// nor a refused continue runs a generator.
func TestStackRebaseStopsOnAGeneratedOnlyConflict(t *testing.T) {
	t.Parallel()
	cmd, marker := regenMarked(t, regenCat)
	f := regenRepo(t, cmd)
	regenBranch(t, f, map[string]string{"src/f.txt": "f\n", "gen/out.txt": "a\nf\n"})
	regenAdvanceTrunk(t, f, [2]string{"src/t.txt", "t\n"}, [2]string{"gen/out.txt", "a\nt\n"})

	ws, err := regenStop(t, f)
	for _, want := range []string{
		"workspace: " + ws + " (detached, sparse, rebase in progress, rerere off)",
		"conflicted files:\n  gen/out.txt\n",
		regenSection(cmd) + " [--include <dir>]... [--full], from " + ws + " once every other file is resolved",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("brief = %v, want %q", err, want)
		}
	}
	if n := regenRuns(t, marker); n != 0 {
		t.Errorf("the generator ran %d time(s) during the rebase, want none", n)
	}
	if unmerged := gitAt(t, f.Env(), ws, "diff", "--name-only", "--diff-filter=U"); unmerged != "gen/out.txt" {
		t.Errorf("unmerged = %q, want gen/out.txt", unmerged)
	}

	_, _, err = runStackCmd(t, f, "continue")
	if err == nil {
		t.Fatal("continue succeeded over an unresolved generated file")
	}
	for _, want := range []string{
		ws + " still has unresolved files: gen/out.txt — resolve them and git add them first\n" + regenSection(cmd),
		"from " + ws + " once every other file is resolved",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("continue = %v, want %q", err, want)
		}
	}
	if n := regenRuns(t, marker); n != 0 {
		t.Errorf("the generator ran %d time(s) during a refused continue, want none", n)
	}
	if unmerged := gitAt(t, f.Env(), ws, "diff", "--name-only", "--diff-filter=U"); unmerged != "gen/out.txt" {
		t.Errorf("unmerged after continue = %q, want gen/out.txt", unmerged)
	}
}

// TestStackRegenerateChecksOutWhatItIsAskedTo pins that the conflict workspace
// holds only the root files and the conflicted directories, so a generator
// reading src/ fails until --include src or --full checks it out.
func TestStackRegenerateChecksOutWhatItIsAskedTo(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name     string
		flags    []string
		wantCone string
		wantLib  bool
	}{
		{"include", []string{"--include", "src"}, "gen\nsrc", false},
		{"full", []string{"--full"}, "", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			cmd, marker := regenMarked(t, regenCat)
			f := regenRepo(t, cmd)
			regenBranch(t, f, map[string]string{"src/f.txt": "f\n", "gen/out.txt": "a\nf\n", "lib/keep.txt": "keep\n"})
			regenAdvanceTrunk(t, f, [2]string{"src/t.txt", "t\n"}, [2]string{"gen/out.txt", "a\nt\n"})
			ws, _ := regenStop(t, f)
			if cone := gitAt(t, f.Env(), ws, "sparse-checkout", "list"); cone != "gen" {
				t.Errorf("cone = %q, want only the conflicted gen", cone)
			}
			for _, name := range []string{"src", "lib"} {
				if _, err := os.Stat(filepath.Join(ws, name)); !errors.Is(err, fs.ErrNotExist) {
					t.Errorf("%s in the workspace: %v, want it not checked out", name, err)
				}
			}

			_, _, err := runStackCmdIn(t, f, ws, "regenerate")
			if err == nil {
				t.Fatal("regenerate succeeded without src checked out")
			}
			for _, want := range []string{"stack regenerate: regenerating gen/out.txt failed, and nothing was committed", "generator `" + cmd + "` exited 1"} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("regenerate = %v, want %q", err, want)
				}
			}
			if !regenMissingSrc.MatchString(err.Error()) {
				t.Errorf("regenerate = %v, want cat's missing src/*.txt, quoted by GNU cat or not by BSD cat", err)
			}
			if unmerged := gitAt(t, f.Env(), ws, "diff", "--name-only", "--diff-filter=U"); unmerged != "gen/out.txt" {
				t.Errorf("unmerged after a failed regenerate = %q, want gen/out.txt", unmerged)
			}

			out, _, err := runStackCmdIn(t, f, ws, append([]string{"regenerate"}, tt.flags...)...)
			if err != nil {
				t.Fatalf("regenerate %v: %v", tt.flags, err)
			}
			if want := "regenerated gen/out.txt" + shipSep + cmd + "\nnext: ccx vcs stack continue"; out != want {
				t.Errorf("regenerate output = %q, want %q", out, want)
			}
			if n := regenRuns(t, marker); n != 2 {
				t.Errorf("the generator ran %d time(s), want once per regenerate", n)
			}
			if got, err := os.ReadFile(filepath.Join(ws, "gen", "out.txt")); err != nil || string(got) != "a\nf\nt\n" {
				t.Errorf("regenerated gen/out.txt = %q, %v, want a, f, t", got, err)
			}
			if tt.wantCone != "" {
				if cone := gitAt(t, f.Env(), ws, "sparse-checkout", "list"); cone != tt.wantCone {
					t.Errorf("cone = %q, want %q", cone, tt.wantCone)
				}
			} else if sparse := gitAt(t, f.Env(), ws, "config", "--get", "core.sparseCheckout"); sparse != "false" {
				t.Errorf("core.sparseCheckout = %q, want false after --full", sparse)
			}
			if tt.wantLib {
				for _, name := range strings.Split(gitAt(t, f.Env(), ws, "ls-files"), "\n") {
					if _, err := os.Stat(filepath.Join(ws, name)); err != nil {
						t.Errorf("tracked %s after --full: %v, want it on disk", name, err)
					}
				}
			} else if _, err := os.Stat(filepath.Join(ws, "lib")); !errors.Is(err, fs.ErrNotExist) {
				t.Errorf("lib after --include src: %v, want it still not checked out", err)
			}

			if _, _, err := runStackCmdIn(t, f, ws, "continue"); err != nil {
				t.Fatalf("continue: %v", err)
			}
			if !stackOnto(t, f, "origin/main", "feature") {
				t.Error("feature is not on the new trunk")
			}
			if got := gitAt(t, f.Env(), f.Dir, "show", "feature:gen/out.txt"); got != "a\nf\nt" {
				t.Errorf("feature's gen/out.txt = %q, want the regenerated a, f, t", got)
			}
			if n := gitAt(t, f.Env(), f.Dir, "rev-list", "--count", "origin/main..feature"); n != "1" {
				t.Errorf("feature holds %s commits over trunk, want its own 1", n)
			}
		})
	}
}

// TestStackBriefReadsTheWorkspaceAfterRegenerateFull pins that a stop after
// regenerate --full describes the workspace it left: every file checked out and
// no sparse cone to widen, rather than the sparse workspace the first stop cut.
func TestStackBriefReadsTheWorkspaceAfterRegenerateFull(t *testing.T) {
	t.Parallel()
	f := regenRepo(t, regenCat)
	writeShipFile(t, f.Dir, "docs/x.txt", "base\n")
	mustRun(t, f.Env(), f.Dir, "git", "add", "docs/x.txt")
	mustRun(t, f.Env(), f.Dir, "git", "commit", "-qm", "docs")
	mustRun(t, f.Env(), f.Dir, "git", "push", "-q", "origin", "main")
	regenBranch(t, f, map[string]string{"src/f.txt": "f\n", "gen/out.txt": "a\nf\n"})
	writeShipFile(t, f.Dir, "docs/x.txt", "branch\n")
	mustRun(t, f.Env(), f.Dir, "git", "commit", "-qam", "docs on the branch")
	regenAdvanceTrunk(t, f, [2]string{"src/t.txt", "t\n"}, [2]string{"gen/out.txt", "a\nt\n"}, [2]string{"docs/x.txt", "trunk\n"})

	ws, err := regenStop(t, f)
	if want := "workspace: " + ws + " (detached, sparse, rebase in progress, rerere off)"; !strings.Contains(err.Error(), want) {
		t.Fatalf("first brief = %v, want %q", err, want)
	}
	if _, _, err := runStackCmdIn(t, f, ws, "regenerate", "--full"); err != nil {
		t.Fatalf("regenerate --full: %v", err)
	}

	_, _, err = runStackCmdIn(t, f, ws, "continue")
	if err == nil {
		t.Fatal("continue succeeded, want the docs/x.txt conflict to stop it")
	}
	brief := err.Error()
	for _, want := range []string{
		"workspace: " + ws + " (detached, rebase in progress, rerere off)",
		"conflicted files:\n  docs/x.txt\n",
		"checked out: every file\n",
	} {
		if !strings.Contains(brief, want) {
			t.Errorf("second brief = %q, want %q", brief, want)
		}
	}
	if strings.Contains(brief, "sparse") {
		t.Errorf("second brief = %q, want no sparse wording for a full workspace", brief)
	}
	if sparse := gitAt(t, f.Env(), ws, "config", "--get", "core.sparseCheckout"); sparse != "false" {
		t.Errorf("core.sparseCheckout = %q, want false after --full", sparse)
	}
}

// TestStackRegenHintReadsTheWorkspaceAfterRegenerateFull pins that a later
// generated conflict in a workspace regenerate --full already checked out in
// full says so, both in the stop's brief and in continue's refusal, rather than
// sending the reader to --include directories that are already there.
func TestStackRegenHintReadsTheWorkspaceAfterRegenerateFull(t *testing.T) {
	t.Parallel()
	f := regenRepo(t, regenCat)
	regenBranch(t, f, map[string]string{"src/f.txt": "f\n", "gen/out.txt": "a\nf\n"})
	writeShipFile(t, f.Dir, "src/g.txt", "g\n")
	writeShipFile(t, f.Dir, "gen/out.txt", "a\nf\ng\n")
	mustRun(t, f.Env(), f.Dir, "git", "add", "src/g.txt", "gen/out.txt")
	mustRun(t, f.Env(), f.Dir, "git", "commit", "-qm", "second generated change")
	regenAdvanceTrunk(t, f, [2]string{"src/t.txt", "t\n"}, [2]string{"gen/out.txt", "a\nt\n"})

	ws, err := regenStop(t, f)
	if want := regenSection(regenCat) + " [--include <dir>]... [--full], from " + ws + " once every other file is resolved — the workspace is sparse"; !strings.Contains(err.Error(), want) {
		t.Fatalf("first brief = %v, want %q", err, want)
	}
	if _, _, err := runStackCmdIn(t, f, ws, "regenerate", "--full"); err != nil {
		t.Fatalf("regenerate --full: %v", err)
	}

	full := regenSection(regenCat) + ", from " + ws + " once every other file is resolved — every file is checked out there, and ccx sets up none of the generator's dependencies there"
	_, _, err = runStackCmdIn(t, f, ws, "continue")
	if err == nil {
		t.Fatal("continue succeeded, want the second gen/out.txt conflict to stop it")
	}
	for _, want := range []string{"conflicted files:\n  gen/out.txt\n", "checked out: every file\n", full + "\n"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("second brief = %q, want %q", err, want)
		}
	}
	if strings.Contains(err.Error(), "sparse") {
		t.Errorf("second brief = %q, want no sparse wording for a full workspace", err)
	}

	_, _, err = runStackCmdIn(t, f, ws, "continue")
	if err == nil || !strings.HasSuffix(err.Error(), full) || strings.Contains(err.Error(), "sparse") {
		t.Errorf("continue over the unresolved conflict = %v, want the refusal to end with %q", err, full)
	}
}

func TestStackRegenerateIncludesDirectoryNamesVerbatim(t *testing.T) {
	t.Parallel()
	const run = "cat ' in[put] '/*.txt > gen/out.txt"
	f := regenRepo(t, run)
	writeShipFile(t, f.Dir, " in[put] /a.txt", "a\n")
	writeShipFile(t, f.Dir, "in[put]/decoy.txt", "decoy\n")
	mustRun(t, f.Env(), f.Dir, "git", "add", "-A")
	mustRun(t, f.Env(), f.Dir, "git", "commit", "-qm", "inputs")
	mustRun(t, f.Env(), f.Dir, "git", "push", "-q", "origin", "main")
	regenBranch(t, f, map[string]string{" in[put] /f.txt": "f\n", "gen/out.txt": "a\nf\n"})
	regenAdvanceTrunk(t, f, [2]string{" in[put] /t.txt", "t\n"}, [2]string{"gen/out.txt", "a\nt\n"})
	ws, _ := regenStop(t, f)

	out, _, err := runStackCmdIn(t, f, ws, "regenerate", "--include", " in[put] ")
	if err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	if want := "regenerated gen/out.txt" + shipSep + run + "\nnext: ccx vcs stack continue"; out != want {
		t.Errorf("regenerate output = %q, want %q", out, want)
	}
	if _, err := os.Stat(filepath.Join(ws, "in[put]")); !os.IsNotExist(err) {
		t.Errorf("in[put]/, which only trims to the included name, is checked out: %v", err)
	}
	if _, _, err := runStackCmdIn(t, f, ws, "continue"); err != nil {
		t.Fatalf("continue: %v", err)
	}
	if got := gitAt(t, f.Env(), f.Dir, "show", "feature:gen/out.txt"); got != "a\nf\nt" {
		t.Errorf("feature's gen/out.txt = %q, want it regenerated from every input", got)
	}
}

func TestStackRegenerateTakesIncludeOrFullNotBoth(t *testing.T) {
	t.Parallel()
	f := regenRepo(t, regenCat)

	_, _, err := runStackCmd(t, f, "regenerate", "--include", "src", "--full")
	if err == nil {
		t.Fatal("regenerate accepted --include with --full")
	}
	if want := "if any flags in the group [include full] are set none of the others can be; [full include] were all set"; err.Error() != want {
		t.Errorf("err = %q, want %q", err, want)
	}
}

func TestStackRegenerateWaitsForTheHandResolvedConflicts(t *testing.T) {
	t.Parallel()
	cmd, marker := regenMarked(t, regenCat)
	f := regenRepo(t, cmd)
	regenBranch(t, f, map[string]string{"src/a.txt": "a-feature\n", "src/f.txt": "f\n", "gen/out.txt": "a-feature\nf\n"})
	regenAdvanceTrunk(t, f, [2]string{"src/a.txt", "a-trunk\n"}, [2]string{"gen/out.txt", "a-trunk\n"})

	ws, err := regenStop(t, f)
	for _, want := range []string{"conflicted files:\n  gen/out.txt\n  src/a.txt\n", regenSection(cmd)} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("brief = %v, want %q", err, want)
		}
	}

	_, _, err = runStackCmdIn(t, f, ws, "regenerate", "--include", "src")
	if err == nil {
		t.Fatal("regenerate succeeded over an unresolved source")
	}
	if want := "stack regenerate: " + ws + " still has unresolved files no generator owns: src/a.txt — resolve them and git add them first"; err.Error() != want {
		t.Errorf("regenerate = %q, want %q", err, want)
	}
	if n := regenRuns(t, marker); n != 0 {
		t.Errorf("the generator ran %d time(s) past an unresolved source, want none", n)
	}

	writeShipFile(t, ws, "src/a.txt", "a-both\n")
	mustRun(t, f.Env(), ws, "git", "add", "src/a.txt")
	out, _, err := runStackCmdIn(t, f, ws, "regenerate", "--include", "src")
	if err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	if want := "regenerated gen/out.txt" + shipSep + cmd + "\nnext: ccx vcs stack continue"; out != want {
		t.Errorf("regenerate output = %q, want %q", out, want)
	}
	if n := regenRuns(t, marker); n != 1 {
		t.Errorf("the generator ran %d time(s), want 1", n)
	}

	out, _, err = runStackCmdIn(t, f, ws, "continue")
	if err != nil {
		t.Fatalf("continue: %v", err)
	}
	if want := stackKeptLine(ws); !strings.Contains(out, want) {
		t.Errorf("continue output = %q, want %q", out, want)
	}
	if got := gitAt(t, f.Env(), f.Dir, "show", "feature:gen/out.txt"); got != "a-both\nf" {
		t.Errorf("feature's gen/out.txt = %q, want it regenerated from the resolved sources", got)
	}
	if got := gitAt(t, f.Env(), f.Dir, "show", "feature:src/a.txt"); got != "a-both" {
		t.Errorf("feature's src/a.txt = %q, want the resolution", got)
	}
}

func TestStackRegenerateRefusesWhenTheStopTouchesNothingGenerated(t *testing.T) {
	t.Parallel()
	cmd, marker := regenMarked(t, regenCat)
	f := regenRepo(t, cmd)
	regenBranch(t, f, map[string]string{"src/a.txt": "a-feature\n"})
	regenAdvanceTrunk(t, f, [2]string{"src/a.txt", "a-trunk\n"})

	ws, err := regenStop(t, f)
	if strings.Contains(err.Error(), "generated by ") {
		t.Errorf("brief = %v, want no generated section for a source-only conflict", err)
	}
	writeShipFile(t, ws, "src/a.txt", "a-both\n")
	mustRun(t, f.Env(), ws, "git", "add", "src/a.txt")

	_, _, err = runStackCmdIn(t, f, ws, "regenerate")
	if err == nil {
		t.Fatal("regenerate succeeded with nothing generated to rerun")
	}
	if want := "stack regenerate: the commit the rebase in " + ws + " stopped on touches nothing " + regenFile + " declares generated — ccx vcs stack continue drives the rebase on"; err.Error() != want {
		t.Errorf("regenerate = %q, want %q", err, want)
	}
	if n := regenRuns(t, marker); n != 0 {
		t.Errorf("the generator ran %d time(s), want none", n)
	}
}

func TestStackRegenerateRerunsEveryGeneratedPathTheStoppedCommitTouches(t *testing.T) {
	t.Parallel()
	const upper = "tr a-z A-Z < gen/out.txt > up/out.txt"
	f := regenRepo(t, regenCat)
	writeShipFile(t, f.Dir, regenFile, fmt.Sprintf("[[generated]]\npaths = [\"gen/*.txt\"]\nrun = %q\n\n[[generated]]\npaths = [\"up/*.txt\"]\nrun = %q\n", regenCat, regenCat+" && "+upper))
	writeShipFile(t, f.Dir, "up/out.txt", "A\n")
	mustRun(t, f.Env(), f.Dir, "git", "add", "-A")
	mustRun(t, f.Env(), f.Dir, "git", "commit", "-qm", "upper")
	mustRun(t, f.Env(), f.Dir, "git", "push", "-q", "origin", "main")
	regenBranch(t, f, map[string]string{"src/f.txt": "f\n", "gen/out.txt": "a\nf\n", "up/out.txt": "A\nF\n"})
	regenAdvanceTrunk(t, f, [2]string{"src/t.txt", "t\n"}, [2]string{"gen/out.txt", "a\nt\n"})

	ws, err := regenStop(t, f)
	if want := regenSection(regenCat); !strings.Contains(err.Error(), want) {
		t.Errorf("brief = %v, want %q", err, want)
	}
	if strings.Contains(err.Error(), "up/out.txt") {
		t.Errorf("brief = %v, want only the conflicted gen/out.txt listed", err)
	}

	out, _, err := runStackCmdIn(t, f, ws, "regenerate", "--include", "src")
	if err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	if want := "regenerated gen/out.txt" + shipSep + regenCat + "\nregenerated up/out.txt" + shipSep + regenCat + " && " + upper + "\nnext: ccx vcs stack continue"; out != want {
		t.Errorf("regenerate output = %q, want %q", out, want)
	}
	if cone := gitAt(t, f.Env(), ws, "sparse-checkout", "list"); cone != "gen\nsrc\nup" {
		t.Errorf("cone = %q, want the conflicted gen, the included src, and up, which the stopped commit touches", cone)
	}

	if _, _, err := runStackCmdIn(t, f, ws, "continue"); err != nil {
		t.Fatalf("continue: %v", err)
	}
	if got := gitAt(t, f.Env(), f.Dir, "show", "feature:up/out.txt"); got != "A\nF\nT" {
		t.Errorf("feature's up/out.txt = %q, want it regenerated over trunk's t", got)
	}
	if got := gitAt(t, f.Env(), f.Dir, "show", "feature:gen/out.txt"); got != "a\nf\nt" {
		t.Errorf("feature's gen/out.txt = %q, want the regenerated a, f, t", got)
	}
}

func TestStackRegenerateKeepsTheReplayedDeletionOfASharedOutput(t *testing.T) {
	t.Parallel()
	const run = "echo regenerated > gen/out.txt; echo refreshed > gen/other.txt"
	f := regenRepo(t, run)
	regenBranch(t, f, map[string]string{"gen/other.txt": "feature\n"}, "gen/out.txt")
	regenAdvanceTrunk(t, f, [2]string{"gen/out.txt", "trunk\n"}, [2]string{"gen/other.txt", "trunk\n"})
	ws, _ := regenStop(t, f)

	out, _, err := runStackCmdIn(t, f, ws, "regenerate")
	if err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	if want := "deleted gen/out.txt" + shipSep + "the replayed commit deletes it\nregenerated gen/other.txt" + shipSep + run + "\nnext: ccx vcs stack continue"; out != want {
		t.Errorf("regenerate output = %q, want %q", out, want)
	}
	if _, _, err := runStackCmdIn(t, f, ws, "continue"); err != nil {
		t.Fatalf("continue: %v", err)
	}
	if got := gitAt(t, f.Env(), f.Dir, "ls-tree", "--name-only", "feature", "gen/"); got != "gen/other.txt" {
		t.Errorf("feature's gen/ = %q, want gen/out.txt still deleted", got)
	}
	if got := gitAt(t, f.Env(), f.Dir, "show", "feature:gen/other.txt"); got != "refreshed" {
		t.Errorf("feature's gen/other.txt = %q, want the shared generator's output", got)
	}
}

func TestStackRegenerateStopsCleanlyOnAFailingGenerator(t *testing.T) {
	t.Parallel()
	const run = "echo generated half > gen/out.txt; echo boom >&2; exit 3"
	f := regenRepo(t, run)
	regenBranch(t, f, map[string]string{"src/f.txt": "f\n", "gen/out.txt": "a\nf\n"})
	regenAdvanceTrunk(t, f, [2]string{"gen/out.txt", "a\nt\n"})
	feature := gitAt(t, f.Env(), f.Dir, "rev-parse", "feature")
	ws, _ := regenStop(t, f)

	_, _, err := runStackCmdIn(t, f, ws, "regenerate")
	if err == nil {
		t.Fatal("regenerate succeeded over a failing generator")
	}
	for _, want := range []string{"stack regenerate: regenerating gen/out.txt failed, and nothing was committed", "generator `" + run + "` exited 3", "output tail:\n  boom"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("regenerate = %v, want %q", err, want)
		}
	}
	if unmerged := gitAt(t, f.Env(), ws, "diff", "--name-only", "--diff-filter=U"); unmerged != "gen/out.txt" {
		t.Errorf("unmerged = %q, want gen/out.txt still conflicted", unmerged)
	}
	if got := gitAt(t, f.Env(), f.Dir, "rev-parse", "feature"); got != feature {
		t.Errorf("feature moved to %s past a failed generator", got)
	}

	out, _, err := runStackCmd(t, f, "abort")
	if err != nil || !strings.Contains(out, "aborted") {
		t.Fatalf("abort = %q, %v", out, err)
	}
	if _, err := os.Stat(ws); !errors.Is(err, fs.ErrNotExist) {
		t.Errorf("workspace after abort: %v, want it removed", err)
	}
	if got := gitAt(t, f.Env(), f.Dir, "rev-parse", "feature"); got != feature {
		t.Errorf("feature moved to %s across an abort", got)
	}
}

func TestStackRegenerateScrubsGitEnvFromTheGenerator(t *testing.T) {
	t.Parallel()
	check := fmt.Sprintf(`for v in %s; do eval "test -z \"\${$v+set}\"" || { echo "$v leaked" >&2; exit 9; }; done; `, strings.Join(regenScrubbed, " "))
	f := regenRepo(t, check+regenCat)
	regenBranch(t, f, map[string]string{"src/f.txt": "f\n", "gen/out.txt": "a\nf\n"})
	regenAdvanceTrunk(t, f, [2]string{"src/t.txt", "t\n"}, [2]string{"gen/out.txt", "a\nt\n"})
	ws, _ := regenStop(t, f)
	gitDir := gitAt(t, f.Env(), ws, "rev-parse", "--absolute-git-dir")
	commonDir := gitAt(t, f.Env(), ws, "rev-parse", "--path-format=absolute", "--git-common-dir")

	cmd := newStackCmd()
	cmd.SilenceUsage, cmd.SilenceErrors = true, true
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"regenerate", "--include", "src"})
	ctx := render.WithEnv(f.ContextIn(ws),
		"GIT_PREFIX=leaked/",
		"GIT_DIR="+gitDir,
		"GIT_WORK_TREE="+ws,
		"GIT_INDEX_FILE="+filepath.Join(gitDir, "index"),
		"GIT_COMMON_DIR="+commonDir,
		"GIT_NO_REPLACE_OBJECTS=1",
	)
	if err := cmd.ExecuteContext(ctx); err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	if want := "regenerated gen/out.txt" + shipSep + check + regenCat; !strings.Contains(out.String(), want) {
		t.Errorf("regenerate output = %q, want %q", out.String(), want)
	}
	if got, err := os.ReadFile(filepath.Join(ws, "gen", "out.txt")); err != nil || string(got) != "a\nf\nt\n" {
		t.Errorf("regenerated gen/out.txt = %q, %v, want a, f, t", got, err)
	}
}

func TestStackContinueCommitsAHandResolvedGeneratedConflict(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		files   map[string]string
		hand    map[string]string
		removed []string
		retired bool
		want    string
	}{
		{
			name:  "edited by hand",
			files: map[string]string{"src/a.txt": "a-feature\n", "gen/out.txt": "a-feature\n"},
			hand:  map[string]string{"src/a.txt": "a-both\n", "gen/out.txt": "a-both by hand\n"},
			want:  "a-both by hand",
		},
		{
			name:    "deleted by hand",
			files:   map[string]string{"src/a.txt": "a-feature\n", "gen/out.txt": "a-feature\n"},
			hand:    map[string]string{"src/a.txt": "a-both\n"},
			removed: []string{"gen/out.txt"},
		},
		{
			name:    "generator retired by the replayed commit",
			files:   map[string]string{regenFile: "", "src/a.txt": "a-feature\n", "gen/out.txt": "a by hand\n"},
			hand:    map[string]string{"src/a.txt": "a-both\n", "gen/out.txt": "a-both by hand\n"},
			retired: true,
			want:    "a-both by hand",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			cmd, marker := regenMarked(t, regenCat)
			f := regenRepo(t, cmd)
			regenBranch(t, f, tt.files)
			regenAdvanceTrunk(t, f, [2]string{"src/a.txt", "a-trunk\n"}, [2]string{"gen/out.txt", "a-trunk\n"})

			ws, err := regenStop(t, f)
			if got := strings.Contains(err.Error(), "generated by "); got == tt.retired {
				t.Errorf("brief = %v, want a generated section = %v", err, !tt.retired)
			}
			for name, content := range tt.hand {
				writeShipFile(t, ws, name, content)
				mustRun(t, f.Env(), ws, "git", "add", name)
			}
			for _, name := range tt.removed {
				mustRun(t, f.Env(), ws, "git", "rm", "-q", name)
			}

			out, _, err := runStackCmdIn(t, f, ws, "continue")
			if err != nil {
				t.Fatalf("continue: %v", err)
			}
			if strings.Contains(out, "regenerated") {
				t.Errorf("continue output = %q, want no generator run", out)
			}
			if n := regenRuns(t, marker); n != 0 {
				t.Errorf("the generator ran %d time(s), want none", n)
			}
			if !stackOnto(t, f, "origin/main", "feature") {
				t.Error("feature is not on the new trunk")
			}
			if tt.want == "" {
				if got := gitAt(t, f.Env(), f.Dir, "ls-tree", "--name-only", "feature", "gen/"); got != "gen/other.txt" {
					t.Errorf("feature's gen/ = %q, want gen/out.txt deleted as resolved", got)
				}
			} else if got := gitAt(t, f.Env(), f.Dir, "show", "feature:gen/out.txt"); got != tt.want {
				t.Errorf("feature's gen/out.txt = %q, want the human's %q", got, tt.want)
			}
		})
	}
}

func TestStackRebaseLeavesACleanlyReplayedGeneratedFileAlone(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		files   map[string]string
		removed []string
		path    string
		want    string
	}{
		{"hand edit of an unconflicted output", map[string]string{"gen/other.txt": "stale by hand\n"}, nil, "gen/other.txt", "stale by hand"},
		{"replayed deletion", nil, []string{"gen/out.txt"}, "gen/out.txt", ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			cmd, marker := regenMarked(t, "echo regenerated > gen/other.txt; "+regenCat)
			f := regenRepo(t, cmd)
			regenBranch(t, f, tt.files, tt.removed...)
			regenAdvanceTrunk(t, f, [2]string{"src/t.txt", "t\n"})

			out, _, err := runStackCmd(t, f, "rebase", "--no-push")
			if err != nil {
				t.Fatalf("stack rebase: %v", err)
			}
			if strings.Contains(out, "regenerated") || strings.Contains(out, "conflict") {
				t.Errorf("output = %q, want a clean rebase with no generator run", out)
			}
			if n := regenRuns(t, marker); n != 0 {
				t.Errorf("the generator ran %d time(s), want none", n)
			}
			if !stackOnto(t, f, "origin/main", "feature") {
				t.Error("feature is not on the new trunk")
			}
			if got := gitAt(t, f.Env(), f.Dir, "ls-tree", "--name-only", "feature", "--", tt.path); (got != "") != (tt.want != "") {
				t.Errorf("feature lists %s as %q, want present = %v", tt.path, got, tt.want != "")
			}
			if tt.want != "" {
				if got := gitAt(t, f.Env(), f.Dir, "show", "feature:"+tt.path); got != tt.want {
					t.Errorf("feature's %s = %q, want %q", tt.path, got, tt.want)
				}
			}
		})
	}
}

func TestRegenGeneratorOwnsEverythingBelowADeclaredDirectory(t *testing.T) {
	t.Parallel()
	g := regenGenerator{Paths: []string{"infra/generated/row-graph", "gen/*.txt"}, Run: "true"}
	tests := []struct {
		path string
		want bool
	}{
		{"infra/generated/row-graph", true},
		{"infra/generated/row-graph/accounts/core.generated.json", true},
		{"infra/generated/row-graph-old/x.json", false},
		{"gen/out.txt", true},
		{"gen/nested/out.txt", false},
	}
	for _, tt := range tests {
		if got := g.owns(tt.path); got != tt.want {
			t.Errorf("owns(%q) = %v, want %v", tt.path, got, tt.want)
		}
	}
}
