"""Tests for the rendered-artifact predicate in ``render_guards``.

Run from the repo root against the captain-hook source env, with ``plugin/`` on the
path so the ``hooks`` package (and its relative imports) resolves::

    PYTHONPATH=plugin/capt-hook uv run --project ../captain-hook --with pytest \
        pytest plugin/capt-hook/hooks/test_render_guards.py

``RenderedArtifact`` stats a sibling ``.claude/fragments/<rel>/layout.toml`` and reads the
target's banner, and ``RenderSource``'s cc-skills ``guides/`` arm reads ``repo_root.name`` —
all disk-dependent, so the Block/True cases run against a real tmp repo tree with the root
pinned on the event. The inline ``tests={}`` in render_guards.py cover only the ALLOW cases a
bare fixture can express; the precise reason-by-reason matrix lives here.
"""

from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

from captain_hook import File

from hooks.render_guards import RenderedArtifact, RenderSource

# A real rendered banner, first line of every migrated artifact (HTML-comment form).
BANNER = (
    "<!-- cc-guides 0.1.11 src=.claude/fragments/AGENTS.md fragments=cc-skills@a91b043b | "
    "GENERATED — do not edit: edit .claude/fragments/AGENTS.md/ and run 'cc-guides render'. -->"
)


def make_evt(path: Path, root: Path | None) -> SimpleNamespace:
    return SimpleNamespace(file=File(path=path), ctx=SimpleNamespace(repo_root=root))


def artifact(root: Path, rel: str, *, banner: str = BANNER, body: str = "# Guide\n", layout: bool = True) -> Path:
    """Materialize an artifact at ``root/rel`` (with the banner) and, when ``layout``, its
    sibling ``.claude/fragments/<rel>/layout.toml`` — the managed-file shape the guard gates on."""
    target = root / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(f"{banner}\n{body}")
    if layout:
        frag = root / ".claude" / "fragments" / rel
        frag.mkdir(parents=True, exist_ok=True)
        (frag / "layout.toml").write_text("[layout]\n")
    return target


class TestRenderedArtifact:
    def test_banner_and_layout_blocks(self, tmp_path: Path) -> None:
        target = artifact(tmp_path, "AGENTS.md")
        assert RenderedArtifact().check(make_evt(target, tmp_path)) is True

    def test_banner_on_second_line_blocks(self, tmp_path: Path) -> None:
        # The banner is a first-OR-second-line stamp; a leading blank line still matches.
        target = artifact(tmp_path, "AGENTS.md", banner="", body=f"{BANNER}\n# Guide\n")
        assert RenderedArtifact().check(make_evt(target, tmp_path)) is True

    def test_nested_shell_artifact_blocks(self, tmp_path: Path) -> None:
        # A rendered install-binary.sh carries the banner in a shell comment; the fragment
        # tree mirrors the full repo-relative path.
        banner = "# cc-guides 0.2.0 src=.claude/fragments/plugin/scripts/install-binary.sh fragments=none | GENERATED"
        target = artifact(tmp_path, "plugin/scripts/install-binary.sh", banner=banner, body="echo hi\n")
        assert RenderedArtifact().check(make_evt(target, tmp_path)) is True

    def test_banner_without_layout_allows(self, tmp_path: Path) -> None:
        # Precision: a banner but no fragment tree (orphaned/copied) is unmanaged → never block.
        target = artifact(tmp_path, "AGENTS.md", layout=False)
        assert RenderedArtifact().check(make_evt(target, tmp_path)) is False

    def test_layout_without_banner_allows(self, tmp_path: Path) -> None:
        # A managed slot but the file has no banner (hand-authored, not yet rendered) → allow.
        target = artifact(tmp_path, "AGENTS.md", banner="# just a heading", body="prose\n")
        assert RenderedArtifact().check(make_evt(target, tmp_path)) is False

    def test_bare_generated_word_allows(self, tmp_path: Path) -> None:
        # Must not fire on a non-artifact that merely contains the word GENERATED, even with a
        # fragment tree present — the full banner shape is required.
        target = artifact(tmp_path, "AGENTS.md", banner="This doc is GENERATED by hand", body="x\n")
        assert RenderedArtifact().check(make_evt(target, tmp_path)) is False

    def test_fragment_source_allows(self, tmp_path: Path) -> None:
        # A fragment SOURCE is never an artifact — excluded so the nudge lane owns it.
        frag = tmp_path / ".claude" / "fragments" / "AGENTS.md"
        frag.mkdir(parents=True)
        (frag / "layout.toml").write_text("[layout]\n")
        part = frag / "part-1.fragment.md"
        part.write_text(f"{BANNER}\nfragment body\n")  # even if it happened to carry a banner
        assert RenderedArtifact().check(make_evt(part, tmp_path)) is False

    def test_unmanaged_source_file_allows(self, tmp_path: Path) -> None:
        target = tmp_path / "internal" / "cli" / "root.go"
        target.parent.mkdir(parents=True)
        target.write_text("package cli\n")
        assert RenderedArtifact().check(make_evt(target, tmp_path)) is False

    def test_missing_file_allows(self, tmp_path: Path) -> None:
        assert RenderedArtifact().check(make_evt(tmp_path / "AGENTS.md", tmp_path)) is False

    def test_no_repo_root_allows(self, tmp_path: Path) -> None:
        target = artifact(tmp_path, "AGENTS.md")
        assert RenderedArtifact().check(make_evt(target, None)) is False

    def test_file_outside_repo_root_allows(self, tmp_path: Path) -> None:
        # A target that does not sit under the repo root can't be repo-relative → allow.
        outside = tmp_path / "outside"
        repo = tmp_path / "repo"
        outside.mkdir()
        repo.mkdir()
        target = artifact(outside, "AGENTS.md")
        assert RenderedArtifact().check(make_evt(target, repo)) is False


class TestRenderSource:
    def test_fragment_edit_warns(self, tmp_path: Path) -> None:
        p = tmp_path / ".claude" / "fragments" / "AGENTS.md" / "part-1.fragment.md"
        assert RenderSource().check(make_evt(p, tmp_path)) is True

    def test_fragment_edit_warns_without_repo_root(self, tmp_path: Path) -> None:
        # The fragment arm is a pure path property — it fires even when repo_root is unknown.
        p = tmp_path / ".claude" / "fragments" / "CLAUDE.md" / "rules.fragment.md"
        assert RenderSource().check(make_evt(p, None)) is True

    def test_cc_skills_guides_warns(self) -> None:
        root = Path("/Users/y/Code/cc-skills")
        assert RenderSource().check(make_evt(root / "guides" / "go-style.md", root)) is True

    def test_guides_outside_cc_skills_allows(self) -> None:
        root = Path("/Users/y/Code/cc-squash")
        assert RenderSource().check(make_evt(root / "guides" / "go-style.md", root)) is False

    def test_cc_skills_non_guides_allows(self) -> None:
        root = Path("/Users/y/Code/cc-skills")
        assert RenderSource().check(make_evt(root / "README.md", root)) is False

    def test_unmanaged_source_allows(self, tmp_path: Path) -> None:
        assert RenderSource().check(make_evt(tmp_path / "internal" / "cli" / "root.go", tmp_path)) is False
